target-version = "py313"

[lint]
select = [
    "ALL",
]

ignore = [
    "ANN401",
    "D203",
    "D212",
    "COM812",
    "ISC001",
]

[lint.flake8-pytest-style]
fixture-parentheses = false

[lint.pyupgrade]
keep-runtime-typing = true

[lint.mccabe]
max-complexity = 25
